### ISSUE TITLE
Cannot update to v3 as post install expects gulp for end user

### ISSUE THREAD

**Issue by ChristopherKiss** [Colonise/Utilities#6]
```
@colonise/utilities@3.0.0 postinstall 
[removed for github]\node_modules\@colonise\utilities
> gulp install

[13:04:17] Local gulp not found in 
[removed for github]\node_modules\@colonise\utilities
[13:04:17] Try running: npm install gulp
```

Wondering if npm has the latest changes? I can't see a post install script.

**Comment by pathurs** [comment]
Oops! Silly me!

**Comment by pathurs** [comment]
@ChristopherKiss If you're willing to help, the code generated is in https://github.com/Colonise/Config/blob/master/source/gulpfile.ts

**Comment by pathurs** [comment]
possible

**Comment by ChristopherKiss** [comment]
@pathurs, I'm definitely wiling, I just don't have capacity. :( Will be a while before I could take a look.

**Comment by pathurs** [comment]
Looks like it should be an easy fix. I could convert the "gulp install" task to a normal promise and then run it from npm itself. Should only take a few hours.

https://github.com/Colonise/Config/blob/21611464c72915d4d4ae4547f27edfa6fbcfddac/source/gulpfile.ts#L298
`export const install = GulpClient.series(unrenameDistributeDefaultFiles, copyDefaultFilesToRoot);`

with

```
export async function () {
    await unrenameDistributeDefaultFiles();
    await copyDefaultFilesToRoot();
}
```

**Comment by ChristopherKiss** [comment]
Thanks @pathurs,

That would be great!

**Comment by pathurs** [comment]
This should be fixed now, please let me know @ChristopherKiss

**Comment by ChristopherKiss** [comment]
@pathurs,

This now works, thank you.
